### ISSUE TITLE
API - mowing doesn't start

### ISSUE THREAD

**Issue by goosst** [EinEinfach/CaSSAndRA#152]
Hello

I seem to have an issue when using the API where the mower doesn't start its undocking and just sticks to charging/docked.

I send this sequence of mqtt messages to cassandra:
1. set mow parameters
2. load a map
3. give the mow command
It often happens: where the state goes to 1) map upload 2) mow 3) back to charging, so it didn't leave his docking station.
This is not a 100% repetitive behaviour, so same commands starts the undocking and mowing in a lot of cases.

If I do the same set of commands through the "manual buttons" in Cassandra, I've never had this situation and it just starts its undocking process guaranteed.

Here you can see state going from charging to upload to mow to docked:
![image](https://github.com/user-attachments/assets/ec92c7d2-40c3-4235-9d58-cf60f3f6847d)

A log of such an event is attached
[test.log](https://github.com/user-attachments/files/16874817/test.log)

the mqtt commands I execute are: 1) setting the mow parameters 2) loading the map 3) giving the mow command (with or without a selection pending which day it is).

**Comment by EinEinfach** [comment]
Ok, I think the problem is the time between map load and mow all command. Cassandra is still changing the map and you command to mow something what isn't available anymore. That is problem in the architecture of Cassandra what I will fix in future. I will send busy to status topic if Cassandra doing some important stuff. And won't accept other commands in this state.

As workaround for you try to add some delay between both commands (30s?) depends on how complex is your map

**Comment by goosst** [comment]
Ok thanks, I'll check it out tomorrow. 
When making the automations, I had the impression the map-upload process only starts after sending the mow command. Was that wrong?

**Comment by EinEinfach** [comment]
To the robot yes, but Cassandra need some calculation for path planning before. It is done once after switching the map.

If you use different tasks instead of different maps then you shouldn't run in this problem

**Comment by goosst** [comment]
Adding the long delay seems to work fine the last several days :)
